### ISSUE TITLE
1.0.1版本 slot" is a reserved attribute and cannot be used as component prop.

### ISSUE THREAD

**Issue by chenhaijia** [hellodigua/vue-danmaku#10]
刚刚使用了最新版 报了这个错 应该是插件内部使用了 slot这个属性作为普通的属性了

**Comment by hellodigua** [comment]
讲道理应该没有1.0.1版本呀，我昨晚发失败了，试试1.0.2版本呢？

chenhaijia <notifications@github.com> 于2021年1月27日周三 上午9:19写道：

**Comment by chenhaijia** [comment]
是1.0.2的问题 我看npm上写了1.0.1 顺手写上去了

**Comment by hellodigua** [comment]
请问能贴一下代码吗，我看一下用法

**Comment by chenhaijia** [comment]
`<template>
  <div
    class="bullet-wrap"
    @click="handerDanmu"
  >
    <vue-danmaku
      class="bullet-inner"
      ref="danmaku"
      :danmus="danmus"
      loop
      :speed="15"
      :channels="4"
      :top="echartfontSize(0.25)"
    >
      <template v-slot:dm="{ danmu }">
        <div class="bullet bullet--medium">
          <div class="bullet-logo">
            <img
              :src="
                danmu.headimgurl ||
                'http://img.wkdao.com/image/system/2019/10/30/1a39acfb9c8ce8f74b3b71e9f7208641.jpg'
              "
              alt="头像"
            />
          </div>
          <div class="bullet-content">
            <div class="bullet-content__time">{{ danmu.time }}</div>
            <div class="bullet-content__word g-ellipsis">
              <span>{{ danmu.nickname }}</span>
              <span v-show="danmu && danmu.mobile">（{{ danmu.mobile }}）</span>
              <span>&nbsp;&nbsp;下单 &nbsp;&nbsp;,&nbsp;&nbsp;</span>
              <span style="color: RGBA(255, 223, 0, 1)">金额￥{{ danmu.pay_fee }}</span>元
            </div>
          </div>
        </div>
      </template>
    </vue-danmaku>
  </div>
</template>
<script>
  import echartfontSize from "../../components/config";
  import vueDanmaku from "vue-danmaku";
  export default {
    props: ["list"],
    components: { vueDanmaku },
    data() {
      return {
        danmus: this.list,
        is_click: false
      };
    },
    methods: {
      echartfontSize: echartfontSize,
      handerDanmu() {
        if (this.is_click) {
          this.$refs['danmaku'].play()
        } else {
          this.$refs['danmaku'].pause()
        }
        this.is_click = !this.is_click;
      }
    },
    watch: {
      list: {
        handler(newVal) {
          if (newVal.length > 0) {
            this.danmus = newVal;
            this.$refs.danmaku.reset()
          }
        },
      },
    },
  };
</script>`

**Comment by chenhaijia** [comment]
![image](https://user-images.githubusercontent.com/49225683/105948103-4ea15b80-60a5-11eb-9252-66e08f7acd8d.png)

**Comment by chenhaijia** [comment]
`
  <vue-danmaku
      class="bullet-inner"
      ref="danmaku"
      :danmus="danmus"
      loop
      :speed="15"
      :channels="4"
      :top="echartfontSize(0.25)"
    >
      <template v-slot:dm="{ danmu }">
        <div class="bullet bullet--medium">
          <div class="bullet-logo">
            <img
              :src="
                danmu.headimgurl ||
                'http://img.wkdao.com/image/system/2019/10/30/1a39acfb9c8ce8f74b3b71e9f7208641.jpg'
              "
              alt="头像"
            />
          </div>
          <div class="bullet-content">
            <div class="bullet-content__time">{{ danmu.time }}</div>
            <div class="bullet-content__word g-ellipsis">
              <span>{{ danmu.nickname }}</span>
              <span v-show="danmu && danmu.mobile">（{{ danmu.mobile }}）</span>
              <span>&nbsp;&nbsp;下单 &nbsp;&nbsp;,&nbsp;&nbsp;</span>
              <span style="color: RGBA(255, 223, 0, 1)">金额￥{{ danmu.pay_fee }}</span>元
            </div>
          </div>
        </div>
      </template>
    </vue-danmaku>
`

**Comment by chenhaijia** [comment]
![image](https://user-images.githubusercontent.com/49225683/105948998-f23f3b80-60a6-11eb-8c32-11c083ffdb64.png)

**Comment by chenhaijia** [comment]
![image](https://user-images.githubusercontent.com/49225683/105949510-c07aa480-60a7-11eb-84b2-311327d403e3.png)
![image](https://user-images.githubusercontent.com/49225683/105949538-cc666680-60a7-11eb-950e-99e449b942de.png)

**Comment by chenhaijia** [comment]
保险起见 暂时了采用上一个版本 目前暂无问题

**Comment by hellodigua** [comment]
我晚上回去看看

**Comment by hellodigua** [comment]
发现一个问题，你是不是没有在参数中指定slot="true"，如果要同时用slot插槽和弹幕插槽的话必须设置 @chenhaijia

**Comment by hellodigua** [comment]
1.0.3版本起使用弹幕插槽需指定:useSlot="true"，以区分命名，可以使用最新版本试试
