### ISSUE TITLE
slot自定义失效（包括源码）

### ISSUE THREAD

**Issue by 2016011969sunyifang** [hellodigua/vue-danmaku#13]
您好，我在项目中用了您的弹幕库 但是发现slot自定义时样式不生效 把您的源码clone下来后发现也不可以
但是在demo演示里是可以的 是不是有什么问题

**Comment by hellodigua** [comment]
请附上您的代码实现和使用的vue-danmaku版本号，谢谢

**Comment by yliaz** [comment]
可以查看下Vue版本，2.6.0之后支持v-slot语法，之前的需要使用slot和slot-scope，详见[Vue插槽](https://cn.vuejs.org/v2/guide/components-slots.html)
```Vue
<template slot="dm" slot-scope="{ index, barrage }">
    <barrage-item></barrage-item>
</template>
```
