### ISSUE TITLE
弹幕不跑有数据按照文档设置 没有弹幕不生成怎么搞啊

### ISSUE THREAD

**Issue by kangzhaorui** [hellodigua/vue-danmaku#14]
### 问题

请在此描述你的问题

### 代码实现

在此附上你遇到问题的代码或代码截图。

```

``` 

### 环境

 - vue-danmaku 版本: [e.g. v1.0.3]
 - Vue 版本: [e.g. v2.0, v2.5, v2.6]

**Comment by hellodigua** [comment]
请贴一下你的代码我看看

**Comment by kangzhaorui** [comment]
可否加个联系方式 ，请教一下。KZR1186785308我的v哇，或者你的v我加你也可以哇   ，感谢大佬 ，希望大佬能给个机会

**Comment by kangzhaorui** [comment]
![image](https://user-images.githubusercontent.com/41569132/111899642-f06f7400-8a68-11eb-9dba-7edbd82e36fd.png)
![image](https://user-images.githubusercontent.com/41569132/111899666-05e49e00-8a69-11eb-9f41-38e81cd1dfdb.png)
现在是这样用的，效果是上面那图的效果 从上往下出来的 而且就卡在那边不动了  没有弹幕的效果

**Comment by hellodigua** [comment]
```
<template>
  <vue-danmaku :danmus="danmus"></vue-danmaku>
</template>

<script>
import vueDanmaku from 'vue-danmaku'

export default {
  data() {
    return {
      danmus: ['danmu1', 'danmu2', 'danmu3', '...'],
    }
  },
}
</script>
```
使用这个最简单的示例看看能跑不

**Comment by hellodigua** [comment]
![image](https://user-images.githubusercontent.com/9943164/111912895-94c3db80-8aa6-11eb-8fc9-e56beb8008b1.png)
应该没有问题
