### ISSUE TITLE
弹幕组件的使用

### ISSUE THREAD

**Issue by missyang-123** [hellodigua/vue-danmaku#15]
我按照代码库提示，安装vue-……，

然后使用插件，但是出现一些问题，

**Comment by hellodigua** [comment]
具体是什么问题，麻烦贴一下报错或者截图

**Comment by missyang-123** [comment]
[新建文本文档.txt](https://github.com/hellodigua/vue-danmaku/files/6943490/default.txt)

**Comment by missyang-123** [comment]
[a.docx](https://github.com/hellodigua/vue-danmaku/files/6943538/a.docx)

**Comment by missyang-123** [comment]
不会贴图，问题在这个文档里面

**Comment by missyang-123** [comment]
[图.docx](https://github.com/hellodigua/vue-danmaku/files/6943621/default.docx)

**Comment by missyang-123** [comment]
我将依赖删掉试试吧
