### ISSUE TITLE
效果问题

### ISSUE THREAD

**Issue by lipeihong** [hellodigua/vue-danmaku#18]
https://user-images.githubusercontent.com/19789697/144443019-cc5a71a5-9ab4-4994-b054-b0e7ee86ebef.mov

**Comment by hellodigua** [comment]
收到，我来看看

**Comment by hellodigua** [comment]
请提供可以复现这个 BUG 的代码，或者可以加 QQ 群 747809274 联系我反馈问题

**Comment by hellodigua** [comment]
已修复
