### ISSUE TITLE
发送有问题

### ISSUE THREAD

**Issue by jellenm** [hellodigua/vue-danmaku#2]
发送消息不能显示

**Comment by hellodigua** [comment]
sorry，现在的版本很多功能都不支持，大概10月份会重构

**Comment by jellenm** [comment]
好的 加油

**Comment by heda20** [comment]
重构可以添加方向吗？除了水平，还有垂直之类的。

**Comment by jellenm** [comment]
重构建议用canvas

**Comment by hellodigua** [comment]
> 重构建议用canvas

难受啊，公司Q4的计划跟自己的计划有部分冲突，10 - 12月要去搞Node和React了，又得搁浅了_(´ཀ`」 ∠)_
