### ISSUE TITLE
弹幕播放完毕后调用add无法正常插入弹幕

### ISSUE THREAD

**Issue by zhaoyifan1996** [hellodigua/vue-danmaku#23]
### 问题

弹幕组件在非loop模式下播放完毕后调用add功能，弹幕会插入到danmuList的首位，弹幕播放的是danmuList最后一条

### 代码实现

https://jsfiddle.net/dtc0yxnr/4/

### 环境

 - vue-danmaku 版本: 1.3.1
 - Vue 版本: 2.6.11

**Comment by hellodigua** [comment]
已在 v1.3.2版本修复
