### ISSUE TITLE
希望能高亮新增的弹幕

### ISSUE THREAD

**Issue by DestinySail** [hellodigua/vue-danmaku#26]
### 问题

我发送了一条弹幕，希望能高亮这条弹幕，如同B站那般

### 代码实现

```

``` 

### 环境

 - vue-danmaku 版本: [e.g. v1.0.3]
 - Vue 版本: [e.g. v2.0, v2.5, v2.6]

**Comment by hellodigua** [comment]
好的，我想一下怎么加

**Comment by hellodigua** [comment]
可以更新到1.4.3版本，push 和 add 方法支持返回插入下标，可以通过判断下标的方式对当前插入弹幕进行样式定制
