### ISSUE TITLE
suspend bug

### ISSUE THREAD

**Issue by jp-liu** [hellodigua/vue-danmaku#29]
### 问题

鼠标悬停弹幕效果, 边缘的弹幕,移入然后移出,会导致弹幕悬停,不会在动了, 问题是节流函数的编写问题, 节流函数是开启了立即触发和尾调用的方式,导致移入方法在后续调用了一次

![danmu](https://user-images.githubusercontent.com/79979500/168722746-bd136ced-8c8a-46a6-9c79-b771504ee9da.gif)

### 代码实现

```html
<script>
  const app = {
    template: `
      <div id="app">
        <vue-danmaku :danmus="danmus" isSuspend loop :channels="4"></vue-danmaku>
      </div>`,
    components: {
      danmaku: window['vue-danmaku'],
    },
    data() {
      return {
        danmus: ['弹幕啊', '弹幕啊1', '弹幕啊2', '弹幕啊3', '弹幕啊4'],
      }
    },
  }
  new Vue({
    render(h) {
      return h(app)
    },
  }).$mount('#app')
</script>
```

### 环境

 - vue-danmaku 版本: [e.g. v1.0.3]
 - Vue 版本: [e.g. v2.0, v2.5, v2.6]

**Comment by jp-liu** [comment]
这里感觉不设置节流也不会有多大的性能损耗,如果触碰的不是弹幕元素,则不会进行操作

**Comment by jp-liu** [comment]
不知道作者意见如何

**Comment by hellodigua** [comment]
OK我晚上测试下，如果性能损耗不大的话下个版本移除掉

**Comment by hellodigua** [comment]
感谢，已修复BUG
