### ISSUE TITLE
容器大小发生变化已生成弹幕移动距离没有跟着变化，when container size change, already generated danmu's moving range didn't change with container

### ISSUE THREAD

**Issue by drake-isc** [hellodigua/vue-danmaku#32]
当我点击播放器全屏，已经发出来的弹幕到达小窗口尺寸的地方就消失了。需要增加判断容器大小变化实时的改变弹幕移动距离。

When I click the full screen of the player, the barrage that has been sent out disappears when it reaches the size of the small window size. It is need to add the real-time change of the barrage movement distance by judging the container size change.

**Comment by hellodigua** [comment]
这部分逻辑需要在外边实现，然后调用组件内置的 resize() 方法重置弹幕容器尺寸
