### ISSUE TITLE
vue3异步获取数据不生效

### ISSUE THREAD

**Issue by Hsugar** [hellodigua/vue-danmaku#33]
<img width="603" alt="image" src="https://user-images.githubusercontent.com/28952469/181005986-91867973-0a77-490f-b4c1-fbc4a5a179fe.png">

props中danmus获取值后，vue3中打印发现，是不是接收存在问题？
导致一直是默认的弹幕，而不是异步获取更新后的数据

**Comment by hellodigua** [comment]
异步获取后是直接给danmus赋值的吗？
如果是的话，建议使用push方法

**Comment by Hsugar** [comment]
> 异步获取后是直接给danmus赋值的吗？ 如果是的话，建议使用push方法

试了push可以满足初始化更新。 感谢~

发弹幕的时候可以实现 重新播放 并且发送的在最前面吗？

我的实现： 先stop、再add 、再play。这样最新输入的弹幕不在最前面 ：）

请问下怎么解决？

**Comment by hellodigua** [comment]
不可以，这些逻辑需要外边自己实现

无非就是保存原始弹幕数据和最新输入的弹幕数据，然后stop之后重新组装

**Comment by Hsugar** [comment]
现在就是重新组装的数据，log中弹幕数据也更新了。

问题： 最新插入的弹幕在数据中是第一条，但是播放弹幕时却不在第一列轨道中

**Comment by hellodigua** [comment]
你是不是设置了随机行显示 `randomChannel ` 这一个属性了

**Comment by Hsugar** [comment]
并没有

**Comment by hellodigua** [comment]
stop之后容器里的弹幕清屏了吗，还是有其他弹幕存在？

**Comment by Hsugar** [comment]
已经清空了。我延迟2秒再重新执行play的

**Comment by hellodigua** [comment]
vue3可能落后了一些版本，可能有一些隐藏BUG，等改天我更新一下

**Comment by hellodigua** [comment]
这个也需要看一下
