### ISSUE TITLE
vue3发送弹幕样式异常

### ISSUE THREAD

**Issue by Hsugar** [hellodigua/vue-danmaku#34]
<img width="343" alt="image" src="https://user-images.githubusercontent.com/28952469/181673570-fc6aaa77-102a-4560-8e0d-7dea243a86ae.png">

发送弹幕时，直接使用add 会出现弹幕异常情况

找了下规律：在前面弹幕与发送弹幕长短差距较大的情况会触发

**Comment by hellodigua** [comment]
收到，周末更新一下vue3的版本

**Comment by Hsugar** [comment]
有更新了吗？

**Comment by hellodigua** [comment]
还没有 追剧荒废了一段时间……最近会更新的

**Comment by Hsugar** [comment]
emmm...这剧应该不错  ：)

**Comment by Hsugar** [comment]
请问计划什么时候更新

**Comment by hellodigua** [comment]
这个周末一定！

**Comment by Hsugar** [comment]
记住 就是明天&明天！

**Comment by hellodigua** [comment]
已更新 `1.0.0-beta.1`，修复了一系列BUG，同步了vue2版本的所有新功能

但是仔细看了看你的描述，感觉你的那个问题应该是自己的样式问题，可能跟组件无关，你更新试试呢

**Comment by Hsugar** [comment]
我检查了，我这边给item的样式只有padding：10px ; 不应该会出现那么大的空白

然后，用了beta版本后，异步赋值&danmaku.value.add() 都失效了。只有默认的弹幕数据。

是api有修改？

**Comment by hellodigua** [comment]
异步赋值有个问题，修复了，但是add不应当啊，你试试更新的呢

1.0.0-beta.2

**Comment by hellodigua** [comment]
> 我检查了，我这边给item的样式只有padding：10px ; 不应该会出现那么大的空白

这一部分能给个复现的demo吗

**Comment by Hsugar** [comment]
微信联系？效率更快

 wx： moleve

**Comment by Hsugar** [comment]
> 异步赋值有个问题，修复了，但是add不应当啊，你试试更新的呢
> 
> 1.0.0-beta.2

我试的新版本还是有问题 

<vue-danmaku   ref="danmaku"  :danmus="barrageArr"/>
barrageArr.value = xxx()

数据如下图：
<img width="376" alt="image" src="https://user-images.githubusercontent.com/28952469/184564674-f744edd9-adf6-409f-8322-6ab78d1607ff.png">
