### ISSUE TITLE
vue3配置了但是还是没显示弹幕

### ISSUE THREAD

**Issue by 932361223** [hellodigua/vue-danmaku#35]
![image](https://user-images.githubusercontent.com/55419238/182030144-cfb5b133-2106-40c6-a596-872debd38cc5.png)
![image](https://user-images.githubusercontent.com/55419238/182030172-f1ea58a5-825e-4aed-9f4e-9d2e5589728f.png)
呐，奇怪

**Comment by 932361223** [comment]
而且也不报错的

**Comment by hellodigua** [comment]
有没有可能，弹幕是白色的，你把背景色换一下

**Comment by 932361223** [comment]
一样的，全部背景都去了还是没显示

**Comment by 932361223** [comment]
https://codepen.io/932361223/pen/rNdpqNw  呐

**Comment by hellodigua** [comment]
可以审查一下元素，确保容器是有宽高的

**Comment by 932361223** [comment]
噢。。。还真是。。。蠢了，谢谢了
