### ISSUE TITLE
安卓端弹幕跳动明细

### ISSUE THREAD

**Issue by Ivynan9419** [hellodigua/vue-danmaku#37]
安卓端弹幕有跳动感，不能平滑移动

**Comment by hellodigua** [comment]
请描述的详细一些，vue2还是vue3，安卓的版本，什么浏览器，具体的配置是什么样，官方Demo可以复现这个问题吗

**Comment by LeiYao123** [comment]
> 安卓端弹幕有跳动感，不能平滑移动

试一下这个 https://github.com/hugeorange/BulletJs  原生 js 实现，性能还算可以
