### ISSUE TITLE
vue3-danmaku.esm.js:223 Uncaught TypeError: Cannot read properties of null (reading 'removeChild')

### ISSUE THREAD

**Issue by xiaoxian521** [hellodigua/vue-danmaku#38]
`dmContainer` 可能不存在哦

复现地址：[open address](https://yiming_chang.gitee.io/vue-pure-admin/#/welcome?username=sso&roles=admin&accessToken=eyJhbGciOiJIUzUxMiJ9.admin)

打开后等 `8` 秒，然后切换别的页面，查看控制台即可定位到报错信息

**Comment by hellodigua** [comment]
好的 这两天修一下
