### ISSUE TITLE
可否加个根据数据中的time来确定出现的时间

### ISSUE THREAD

**Issue by daijun123** [hellodigua/vue-danmaku#42]
### 问题

可否加个根据数据中的time来确定出现的时间，主要是如果只有一条弹幕的时候开启轮询效果很差

### 环境

 - vue-danmaku 版本: [v1.4]
 - Vue 版本: [v3.2]

**Comment by hellodigua** [comment]
这种情况就不要使用v-model了，也不要开启loop，可以直接使用提供的insert方法去发起弹幕，insert方法不会被双向绑定

然后你在外部去维护一个计时器，根据计时器的时间去插入弹幕
