### ISSUE TITLE
为什么.dm里有这么一个鬼属性啊？

### ISSUE THREAD

**Issue by lizy-CZ** [hellodigua/vue-danmaku#44]
### 问题
.dm {
  white-space: pre;
}
请在此描述你的问题
prettier 格式化代码后会导致显示排版出错

### 代码实现

在此附上你遇到问题的代码或代码截图。

```

``` 

### 环境

 - vue-danmaku 版本: [e.g. v1.0.3]
 - Vue 版本: [e.g. v2.0, v2.5, v2.6]

**Comment by hellodigua** [comment]
prettier 格式化代码后会导致显示排版出错，是指弹幕的显示出错吗

**Comment by lizy-CZ** [comment]
![image](https://github.com/hellodigua/vue-danmaku/assets/103976180/912acacf-217b-4408-b661-34d0eba74bf5)
会导致保留所有空格

::v-deep .vue-danmaku .danmus .dm {
    white-space: nowrap !important;
}

后恢复正常

**Comment by hellodigua** [comment]
这个最主要的作用其实是确保文本不会换行，如果输入前有换行或者空格建议输入前加个函数过滤掉的
