### ISSUE TITLE
vue2，我发现会出现弹幕重叠。双向绑定的数组

### ISSUE THREAD

**Issue by suruozhong** [hellodigua/vue-danmaku#45]
1、发现弹幕会重叠
2、双向绑定的array，如果一直add进去数据，久了是否会造成array数据太多，内存占用多，页面卡顿。这个array数量要自己控制吗？

**Comment by hellodigua** [comment]
问题1，能否提供一个可复现的Demo？

问题2，array数量是需要自己控制的，如果不想控制，那么可以使用insert方法，insert会实时插入，不进行数据绑定。

**Comment by suruozhong** [comment]
好的，谢谢
问题1：我再观察看看
