### ISSUE TITLE
调整视口后弹幕显示不正常

### ISSUE THREAD

**Issue by erduoLeading** [hellodigua/vue-danmaku#46]
### 问题
调整屏幕后弹幕没有重置

正常情况
![image](https://github.com/hellodigua/vue-danmaku/assets/38006111/212e0981-d5d6-4b43-9e6e-bc9d812962d7)

改变窗口
![image](https://github.com/hellodigua/vue-danmaku/assets/38006111/12a43656-a864-46e8-af8f-87fe92495754)

问题：
后面出现的弹幕出现重叠并且不会有动画，间距等会问题

添加了重置代码不生效
### 代码实现
![image](https://github.com/hellodigua/vue-danmaku/assets/38006111/0d09d770-cc65-4185-be6a-54fb6a2befaf)

```
<template>
  <!-- 自定义 -->
  <vue-danmaku class="danmuku" ref="danmaku" v-model="danmus" use-slot loop :speeds="speeds" :channels="2" :top="10" :right="0">
    <!-- 弹幕插槽（vue 2.6.0 以下请使用 slot-scope语法） -->
    <template slot="dm" slot-scope="{ index, danmu }">
      <div :class="['item', {
        'superChest': danmu.isSuperChest
      }]">
        <img class="avatar" :src="danmu.avatar" alt="">
        <span class="msg ">{{ danmu.msg }}</span>
      </div>
    </template>

    <!-- 容器插槽 -->
  </vue-danmaku>
</template>

<script>
import vueDanmaku from 'vue-danmaku'

export default {
  props: {
    speeds: { // 每秒移动的像素数 （数值越大速率越快)
      type: Number,
      default: 50,
    },
    channels: { // 通道数
      type: Number,
      default: 2
    }
  },
  watch: {
    mixinStoreTrend (nVal) {
      this.danmus = nVal
    }
  },
  components: {
    vueDanmaku
  },
  data () {
    return {
      danmus: [
        // {
        //   msg : '坐牢！坐牢！坐牢！',
        //   avatar: '',
        // },
      ],
    }
  },
  mounted () {
    // 结合mixin,初始化或抽奖成功后实时调用
    this.mixinDispatchStoreTrend()
    console.log(this.$refs.danmaku, this.$refs.danmaku.resize)
    window.addEventListener('resize', () => {
      this.$refs.danmaku.stop()
      this.$refs.danmaku.reset()
      this.$refs.danmaku.resize()
      this.danmus = []
      setTimeout(() => {
        this.danmus = this.mixinStoreTrend
        this.$refs.danmaku.play()
        console.log(1111)
      },500)

      
    })

  }
}
</script>
<style lang='scss' scoped>
.danmuku {
  position: absolute;
  top: 353px;
  width: 750px;
  height: 180px;

  .item {
    display: flex;
    align-items: center;
    height: 40px;
    background: rgba(14, 0, 52, 0.6);
    border-radius: 25px 25px 25px 25px;
    opacity: 1;
    padding: 0 10px 0 5px;

    &.superChest {
      background: linear-gradient(270deg, #3D07FF 0%, #FB00FF 100%);
    }

    .avatar {
      width: 30px;
      height: 30px;
      margin-right: 20px;
      border-radius: 50%;
    }

    .msg {

      font-size: 24px;
      font-family: Source Han Sans CN-Regular, Source Han Sans CN;
      font-weight: 400;
      color: #FFFFFF;

    }
  }
}
</style>

``` 

### 环境

 -   "vue-danmaku": "^1.7.0",
 -   "vue": "^2.6.11",

**Comment by hellodigua** [comment]
复现出来了，这两天修一下

**Comment by sanqi377** [comment]
@erduoLeading #47

**Comment by hellodigua** [comment]
vue2版本已更新 v1.7.1 麻烦试一下

**Comment by erduoLeading** [comment]
看了下不兼容vivo android 7.1机型 都打开不了   是不是用了一些新es语法糖，比如 ?. 之类的

**Comment by hellodigua** [comment]
> 看了下不兼容vivo android 7.1机型 项目都打开不了 是不是用了一些新es语法糖，比如 ?. 之类的

你是说引用了v1.7.1新版本以后就打开不了了吗？还是说连旧版本也打开不了？

如果旧版本打开不了的话，能发一下控制台的报错吗？

**Comment by erduoLeading** [comment]
> > > > 看了下不兼容vivo android 7.1机型 项目都打开不了 是不是用了一些新es语法糖，比如 ?. 之类的
> > > 
> > > 
> > > 你是说引用了v1.7.1新版本以后就打开不了了吗？还是说连旧版本也打开不了？
> > > 如果旧版本打开不了的话，能发一下控制台的报错吗？
> > 
> > 
> > android7的机型不兼容， android8 可以，可以看下能不能兼容
> 
> 你现在用的是哪个版本呢，v1.7.1还是v1.7.0？v1.7.0也不行吗？我需要先排除是不是新版本的问题

1.7.0

**Comment by hellodigua** [comment]
> > > > > 看了下不兼容vivo android 7.1机型 项目都打开不了 是不是用了一些新es语法糖，比如 ?. 之类的
> > > > 
> > > > 
> > > > 你是说引用了v1.7.1新版本以后就打开不了了吗？还是说连旧版本也打开不了？
> > > > 如果旧版本打开不了的话，能发一下控制台的报错吗？
> > > 
> > > 
> > > android7的机型不兼容， android8 可以，可以看下能不能兼容
> > 
> > 
> > 你现在用的是哪个版本呢，v1.7.1还是v1.7.0？v1.7.0也不行吗？我需要先排除是不是新版本的问题
> 
> 1.7.0

好吧，排除兼容问题，?. 之类的新语法糖也是没有用到的

另外我没有android7的测试机，希望你能看一下报什么错，然后我来修复

**Comment by hellodigua** [comment]
> > > > > > > 看了下不兼容vivo android 7.1机型 项目都打开不了 是不是用了一些新es语法糖，比如 ?. 之类的
> > > > > > 
> > > > > > 
> > > > > > 你是说引用了v1.7.1新版本以后就打开不了了吗？还是说连旧版本也打开不了？
> > > > > > 如果旧版本打开不了的话，能发一下控制台的报错吗？
> > > > > 
> > > > > 
> > > > > android7的机型不兼容， android8 可以，可以看下能不能兼容
> > > > 
> > > > 
> > > > 你现在用的是哪个版本呢，v1.7.1还是v1.7.0？v1.7.0也不行吗？我需要先排除是不是新版本的问题
> > > 
> > > 
> > > 1.7.0
> > 
> > 
> > 好吧，排除兼容问题，?. 之类的新语法糖也是没有用到的
> > 另外我没有android7的测试机，希望你能看一下报什么错，然后我来修复
> 
> 他主要是放到webview里面就不行了，浏览器可以，报错是源码内的报错，看不了，用sourmap也没用 ![img_v2_a80b8276-9433-45d9-a092-7cdda7d89abg](https://user-images.githubusercontent.com/38006111/255851679-bc07903d-a1ce-489f-83e0-57f0ea94288f.jpg)

你可以直接把弹幕的源码放到里面跑的，我这个组件其实就是一个单文件组件，没其他依赖项，你直接把这个文件拷贝进去看看呢 https://github.com/hellodigua/vue-danmaku/blob/master/src/lib/main.vue

**Comment by erduoLeading** [comment]
![image](https://github.com/hellodigua/vue-danmaku/assets/38006111/ee1c992f-c6b7-41b7-b132-9239681e7cd6)
排查到了，同时说这个东西有兼容性问题。指定了1.7.0版本之后去用在webivew中android 6系统是兼容的，能正常显示。

**Comment by hellodigua** [comment]
> ![image](https://user-images.githubusercontent.com/38006111/256101489-ee1c992f-c6b7-41b7-b132-9239681e7cd6.png) 排查到了，这个东西有兼容性问题。指定了1.7.0版本之后去用在webivew中android 6系统是兼容的，能正常显示。之前是因为vconsole那插件版本过高导致没排查出来，我们再调试调试确认下

你前面不是用的v1.7.0吗，我之前问你用的v1.7.1还是v1.7.0，意思就是希望排查是不是这部分代码有问题的，这段代码只在v1.7.1存在

**Comment by erduoLeading** [comment]
> > ![image](https://user-images.githubusercontent.com/38006111/256101489-ee1c992f-c6b7-41b7-b132-9239681e7cd6.png) 排查到了，这个东西有兼容性问题。指定了1.7.0版本之后去用在webivew中android 6系统是兼容的，能正常显示。之前是因为vconsole那插件版本过高导致没排查出来，我们再调试调试确认下
> 
> 你前面不是用的v1.7.0吗，我之前问你用的v1.7.1还是v1.7.0，意思就是希望排查是不是这部分代码有问题的，这段代码只在v1.7.1存在

嗯嗯，有看到的，之前用的^1.7.0会采用1.7下的高版本。尝试切换了v1.7.0但是没排查出来，主要有其他插件版本过高也导致页面无法显示，不确定是不是上述的ResizeObserver导致的，所以没给确切答复。去掉了其他插件之后，再将danmuku降低到1.7.0，发现还有问题才确定是ResizeObserver导致的。

**Comment by hellodigua** [comment]
> > > ![image](https://user-images.githubusercontent.com/38006111/256101489-ee1c992f-c6b7-41b7-b132-9239681e7cd6.png) 排查到了，这个东西有兼容性问题。指定了1.7.0版本之后去用在webivew中android 6系统是兼容的，能正常显示。之前是因为vconsole那插件版本过高导致没排查出来，我们再调试调试确认下
> > 
> > 
> > 你前面不是用的v1.7.0吗，我之前问你用的v1.7.1还是v1.7.0，意思就是希望排查是不是这部分代码有问题的，这段代码只在v1.7.1存在
> 
> 嗯嗯，有看到的，之前用的^1.7.0会采用1.7下的高版本。尝试切换了v1.7.0但是没排查出来，主要有其他插件版本过高也导致页面无法显示，不确定是不是上述的ResizeObserver导致的，所以没给确切答复。去掉了其他插件之后，再将danmuku降低到1.7.0，发现还有问题才确定是ResizeObserver导致的。

好的感谢排查，我会移除掉这个版本
