### ISSUE TITLE
父组件resize后弹幕组件内的containerWidth 跟 containerHeight不会改变

### ISSUE THREAD

**Issue by sanqi377** [hellodigua/vue-danmaku#47]
### 问题

父组件resize后弹幕组件内的containerWidth 跟 containerHeight不会改变，导致弹幕绘制位置不正确，css left错误

### 代码实现

<img width="1149" alt="image" src="https://github.com/hellodigua/vue-danmaku/assets/75518418/c03fbe68-ff8f-49b4-86f8-922b0a655a26">

<img width="810" alt="image" src="https://github.com/hellodigua/vue-danmaku/assets/75518418/59266e15-a391-4aa7-8a9c-ef92c1ea5b6b">

一般是不会有这个问题的，我们业务出这个问题是因为大屏自适应，在父级加了 zoom 后会改变组件的 offsetWidth 跟 offsetHeight。导致绘制的位置不对。

```

``` 

### 环境

 - vue-danmaku 版本: [v1.4.0]
 - Vue 版本: [V3.2.45]

**Comment by sanqi377** [comment]
解决方案：

**Comment by hellodigua** [comment]
感谢，v1.5.0已更新这部分代码
