### ISSUE TITLE
停用缓存头像会一直被重复请求

### ISSUE THREAD

**Issue by erduoLeading** [hellodigua/vue-danmaku#48]
### 问题
停用缓存，请求会一直加载图片资源

![image](https://github.com/hellodigua/vue-danmaku/assets/38006111/43ad8c78-cb94-4a36-b772-16348353d16c)

### 代码实现

在此附上你遇到问题的代码或代码截图。

```

``` 

### 环境

"vue-danmaku": "^1.7.0",
"vue": "^2.6.11",

**Comment by hellodigua** [comment]
因为你使用了网络图片，如果是固定的图片的话，建议使用base64吧

**Comment by erduoLeading** [comment]
后端给的头像是非固定的，总共才21条数据，停用缓存后直接无限请求

**Comment by erduoLeading** [comment]
> 

后端给的头像是非固定的，总共才21条数据，停用缓存后直接无限请求

**Comment by hellodigua** [comment]
没什么办法，因为你停用网络缓存了，那你可以想办法实现本地缓存的逻辑
