### ISSUE TITLE
nuxt3运行中报错 Cannot read properties of undefined (reading 'defineComponent')

### ISSUE THREAD

**Issue by joshsyj** [hellodigua/vue-danmaku#49]

**Comment by hellodigua** [comment]
请附上使用的vue版本、vue-danmaku版本，nuxt3版本

**Comment by joshsyj** [comment]
"vue3-danmaku": "^1.5.1",
"nuxt": "3.5.0",
"vue": "3.3.4"

**Comment by hellodigua** [comment]
nuxt项目需要在组件外包裹一层<client-only></client-only>

**Comment by qq651901286** [comment]
具体怎么操作呀，新手学Nuxt3中 @hellodigua

**Comment by hellodigua** [comment]
> 具体怎么操作呀，新手学Nuxt3中 @hellodigua

nuxt项目需要在组件外包裹一层 <client-only></client-only>

**Comment by qq651901286** [comment]
![image](https://github.com/hellodigua/vue-danmaku/assets/60742716/4f3e9c2d-f7b3-43fb-9fc9-9597783ee8ab)

**Comment by hellodigua** [comment]
发一下gitee的仓库我去跑跑看

**Comment by qq651901286** [comment]
麻烦大佬了  https://gitee.com/qq651901286/vue-danmaku_test.git @hellodigua
