### ISSUE TITLE
大神能不能帮调下在IOS下能播放弹幕的问题

### ISSUE THREAD

**Issue by crazyblz** [hellodigua/vue-danmaku#5]
我现在能定位到问题是在IOS上播放动画时transform 貌似失效了，但我找不到解决方案。大神劳烦给个解决方案，你的demo也在ios下无法运行。好不容易集成到自己的项目里了 结果ios出问题了。好揪心啊

**Comment by hellodigua** [comment]
不好意思，两年前我还没有苹果设备所以没有测试iOS下的兼容性，今晚在safari上测试了，这个问题确实存在，已经发版修复了这个BUG，请安装vue-danmaku@0.1.0 版本试试看是否恢复正常(●'◡'●)ﾉ♥

**Comment by crazyblz** [comment]
收到谢谢，我也解决了 动画是from 和to的问题
