### ISSUE TITLE
Nuxt3使用ref报错

### ISSUE THREAD

**Issue by qq651901286** [hellodigua/vue-danmaku#50]
Nuxt3使用ref报错

<vue-danmaku ref="danmakuRef"></vue-danmaku>

setup() {
  const danmakuRef = ref(null)

  danmakuRef.value.play()
}
大佬可以帮忙看看嘛

**Comment by qq651901286** [comment]
问题已解决，在
  nextTick(()=>{
    console.log(danmakuRef.value)
  })调用

![image](https://github.com/hellodigua/vue-danmaku/assets/60742716/7bfcd541-40c0-42e6-9eb0-4a340d6742e5)


但是Nuxt存在一个问题就是，第二次进入该页面时，没有显示弹幕
项目地址
https://gitee.com/qq651901286/qixiao_blog_nuxt3.git

**Comment by hellodigua** [comment]
在 danmakuRef.value.play() 前面 加一行 danmakuRef.value.stop() 试试？

**Comment by qq651901286** [comment]
不太行

**Comment by hellodigua** [comment]
你的那个页面，刚进入的时候组件获取到的容器宽度是0，所以没展示，得延迟一点时间，然后重新获取宽度后播放

```
onMounted(() => {
  nextTick(() => {
    setTimeout(() => {
      danmakuRef.value.resize();
      danmakuRef.value.play();
    }, 100);
  });
});
```
