### ISSUE TITLE
元素发生重叠

### ISSUE THREAD

**Issue by abcdftg** [hellodigua/vue-danmaku#52]
### 问题

请在此描述你的问题
如果用插槽的形式每个元素高度不一样的话  会出现重叠问题。 因为一开始轨道计算好了 随后如果单一元素高度过大就重叠了 ，麻烦大佬解决下

### 代码实现

在此附上你遇到问题的代码或代码截图。

```

``` 

### 环境

 - vue-danmaku 版本: [e.g. v1.0.3]
 - Vue 版本: [e.g. v2.0, v2.5, v2.6]

**Comment by hellodigua** [comment]
涉及到核心代码的重构，可能需要等待下一个大版本，最近应该没时间。
目前我能想到的解决方案是，给单个弹幕的最大高度设置的高一些，这样就可以让所以弹幕高度保持一致了。
