### ISSUE TITLE
删除其中一条弹幕，或者修改其他某条弹幕数据时，视图内容不会更新

### ISSUE THREAD

**Issue by unique-LN** [hellodigua/vue-danmaku#53]
### 问题

请在此描述你的问题

slot模式下
1. 删除其他一条弹幕，视图不更新，下一轮循环才更新
2. 修改某条弹幕的属性，比如点赞数目，视图不更新，下一轮循环才更新

打断点看这里的数据已经更新了
![image](https://github.com/hellodigua/vue-danmaku/assets/115520155/cbfc4655-79ce-463d-9990-a53cd94eb5a4)

### 代码实现

在此附上你遇到问题的代码或代码截图。

```

``` 

### 环境

 - vue-danmaku 版本: [e.g. v1.7.2]
 - Vue 版本: [v2.0]

**Comment by unique-LN** [comment]
已经自己在业务层解决

**Comment by hellodigua** [comment]
请问能说一下怎么解决的吗，当时看到这条issue还没啥思路

**Comment by unique-LN** [comment]
删除的我是用样式控制直接隐藏了，就是维护了一个需要删除的id数组，视图就可以更新了，因为数据层是可以删除的，之前只是视图不更新
编辑的我还没找到很好的解决方案，就是给了一个傻瓜方案，读到当前这条的位置，在外面写了可以更新的操作覆盖了那一个，鼠标移出的时候就隐藏了
