### ISSUE TITLE
弹幕安全距离判断疑问

### ISSUE THREAD

**Issue by bianyinglong** [hellodigua/vue-danmaku#55]
### 问题

请在此描述你的问题

请问下这个判断逻辑是啥意思，不太明白为啥要判断当前弹幕和轨道内所有弹幕的宽度差值？我看去掉```danRight <= (el.offsetWidth - items[j].offsetWidth) * 0.88```后弹幕会互相遮挡，能解释下是怎么避免弹幕之间互相遮挡的逻辑的吗？

### 代码实现

<img width="754" alt="image" src="https://github.com/hellodigua/vue-danmaku/assets/55875851/13057250-de85-4d6e-8290-1a0bcb88eb7a">

```

``` 

### 环境

 - vue-danmaku 版本: [1.6.0]
 - Vue 版本: [v3]

**Comment by bianyinglong** [comment]
感谢回复，请问这个`(el.offsetWidth - items[j].offsetWidth) * [0.88`算式没有啥科学依据吗，还是就是试出来的，如果是试出来的我感觉可以根据车辆追及问题去判断，比较好理解，可以参考( https://mrluo.life/article/detail/146/danmaku-implement)这篇文章里的计算

另外发现一个问题，就是外部insert弹幕的时候，如果所有轨道都不满足插入条件，则该条弹幕会被丢弃，不会有上屏效果，不知道是就是这么设计的还是个bug ?

**Comment by hellodigua** [comment]
我在写的时候也参考了b站的弹幕系统，这里的科学依据我也说不清了，你就当是试出来的吧，或者你可以考虑重写
对于第2个问题，应该算是bug的，这个逻辑我没有考虑到
