### ISSUE TITLE
设置轨道数channels为0后，弹幕容器大小为全屏，但是弹幕没在全屏显示，长时间只在顶部显示。为5个轨道的宽度

### ISSUE THREAD

**Issue by tmyaushio** [hellodigua/vue-danmaku#56]
<vue-danmaku
        ref="danmaku"
        v-model:danmus="danmus"
        :useSlot="useSlot"
        loop
        :channels="0"
        :top="6"
        style="height: 100%; width: 100%"
      >
        <template v-slot:dm="{ danmu }">
          <div class="danmu flex-r">
            <el-image></el-image><span>{{ danmu.name }}{{ danmu.text }}</span>
          </div>
        </template>
      </vue-danmaku>

**Comment by hellodigua** [comment]
可以附上demo吗

**Comment by tmyaushio** [comment]
好的，不过压缩后体积也比较大，这是项目地址https://gitee.com/ushio123/ushio-website-fontend，然后我把bug图片发给你看看
[Uploading bug图片展示.zip…]()

**Comment by hellodigua** [comment]
我知道原因了，因为弹幕的默认设置是从上往下寻找轨道插入，因为顶部的轨道还有内容，所以就会插入，下面的弹道压根没机会进入弹幕。

你可以多插入一些弹幕，包括字数长的弹幕，这样就能解决这个问题。

另外你可以设置 randomChannel 参数，随机插入效果会更好

**Comment by tmyaushio** [comment]
好的，非常感谢！！！
