### ISSUE TITLE
弹幕宽高是根据窗口宽高获取的，但是弹幕显示不出来

### ISSUE THREAD

**Issue by Elliot-Zhangyx** [hellodigua/vue-danmaku#57]
我的弹幕宽高是根据窗口宽高获取的，但是弹幕显示不出来，换成指定数字就能显示出来了，这个要怎么解决
`
           <vue-danmaku 
              v-model="danmus"
              :isSuspend="true"
              loop
              :fontSize='25'
              :style="{height:wrapSize.height/2+'px',width:wrapSize.width+'px',margin:'5px 0','box-shadow': '1px'}"
              ref="danmaku"
              @play-end="end">
            </vue-danmaku>
`
wrapSize是
` wrapSize:{width:0,height:0},`
如果直接给wrapSize的width或者height赋值是可以的，但是在mounted中赋值就不行了，有更好的解决方法吗

**Comment by hellodigua** [comment]
必须依赖指定的宽高，你要么就给个100%都行，不能给0

**Comment by Elliot-Zhangyx** [comment]
好的，谢谢，vue2版本的可以增加弹幕悬浮暂停相关事件吗

**Comment by hellodigua** [comment]
挺好加的，你参考vue3的自己加上吧，vue2的实在懒得维护了
