### ISSUE TITLE
this dependency was not found:

### ISSUE THREAD

**Issue by lcy7** [hellodigua/vue-danmaku#6]
我下载之后，还是提示这个东西没找到

**Comment by hellodigua** [comment]
请附上你的代码实现，我看看是哪里出了问题

**Comment by lcy7** [comment]
<template>
  <div>
    <vue-danmaku ref="danmaku" :danmus="danmus" :config="config" @inited="onInit">
      <slot></slot>
    </vue-danmaku>
  </div>
</template>

<script>
import vueDanmaku from 'vue-danmaku'
export default {
  components: {
    vueDanmaku
  },
  data() {
    return {
      danmus: ['danmu1', 'danmu2', 'danmu3', 'danmu4', '...'],
      config: {
        channels: 5,
        loop: true,
        speed: 5,
        fontSize: 20
      }
    }
  }
}
</script>

<style lang="less" scoped>

</style>

**Comment by lcy7** [comment]
<template>
  <div>
    <vue-danmaku ref="danmaku" :danmus="danmus" :config="config" @inited="onInit">
      <slot></slot>
    </vue-danmaku>
  </div>
</template>

<script>
import vueDanmaku from 'vue-danmaku'
export default {
  components: {
    vueDanmaku
  },
  data() {
    return {
      danmus: ['danmu1', 'danmu2', 'danmu3', 'danmu4', '...'],
      config: {
        channels: 5,
        loop: true,
        speed: 5,
        fontSize: 20
      }
    }
  }
}
</script>

<style lang="less" scoped>

</style>

**Comment by lcy7** [comment]
`<template>
  <div>
    <vue-danmaku ref="danmaku" :danmus="danmus" :config="config" @inited="onInit">
      <slot></slot>
    </vue-danmaku>
  </div>
</template>

<script>
import vueDanmaku from 'vue-danmaku'
export default {
  components: {
    vueDanmaku
  },
  data() {
    return {
      danmus: ['danmu1', 'danmu2', 'danmu3', 'danmu4', '...'],
      config: {
        channels: 5,
        loop: true,
        speed: 5,
        fontSize: 20
      }
    }
  }
}
</script>

<style lang="less" scoped>

</style>`

**Comment by lcy7** [comment]
<template>
  <div>
    <vue-danmaku ref="danmaku" :danmus="danmus" :config="config" @inited="onInit">
      <slot></slot>
    </vue-danmaku>
  </div>
</template>

<script>
import vueDanmaku from 'vue-danmaku'
export default {
  components: {
    vueDanmaku
  },
  data() {
    return {
      danmus: ['danmu1', 'danmu2', 'danmu3', 'danmu4', '...'],
      config: {
        channels: 5,
        loop: true,
        speed: 5,
        fontSize: 20
      }
    }
  }
}
</script>

<style lang="less" scoped>

</style>

**Comment by lcy7** [comment]
<template>
  <div>
    <vue-danmaku ref="danmaku" :danmus="danmus" :config="config" @inited="onInit">
      <slot></slot>
    </vue-danmaku>
  </div>
</template>

<script>
import vueDanmaku from 'vue-danmaku'
export default {
  components: {
    vueDanmaku
  },
  data() {
    return {
      danmus: ['danmu1', 'danmu2', 'danmu3', 'danmu4', '...'],
      config: {
        channels: 5,
        loop: true,
        speed: 5,
        fontSize: 20
      }
    }
  }
}
</script>

<style lang="less" scoped>

</style>

**Comment by lcy7** [comment]
我的代码
`<template>
  <div>
    <vue-danmaku ref="danmaku" :danmus="danmus" :config="config" @inited="onInit">
      <slot></slot>
    </vue-danmaku>
  </div>
</template>

<script>
import vueDanmaku from 'vue-danmaku'
export default {
  components: {
    vueDanmaku
  },
  data() {
    return {
      danmus: ['danmu1', 'danmu2', 'danmu3', 'danmu4', '...'],
      config: {
        channels: 5,
        loop: true,
        speed: 5,
        fontSize: 20
      }
    }
  }
}
</script>

<style lang="less" scoped>

</style>`

**Comment by lcy7** [comment]
> 请附上你的代码实现，我看看是哪里出了问题

`<template>
  <div>
    <vue-danmaku ref="danmaku" :danmus="danmus" :config="config" @inited="onInit">
      <slot></slot>
    </vue-danmaku>
  </div>
</template>

<script>
import vueDanmaku from 'vue-danmaku'
export default {
  components: {
    vueDanmaku
  },
  data() {
    return {
      danmus: ['danmu1', 'danmu2', 'danmu3', 'danmu4', '...'],
      config: {
        channels: 5,
        loop: true,
        speed: 5,
        fontSize: 20
      }
    }
  }
}
</script>

<style lang="less" scoped>

</style>`

**Comment by lcy7** [comment]
> 请附上你的代码实现，我看看是哪里出了问题

> <template>
  <div>
    <vue-danmaku ref="danmaku" :danmus="danmus" :config="config" @inited="onInit">
      <slot></slot>
    </vue-danmaku>
  </div>
</template>

<script>
import vueDanmaku from 'vue-danmaku'
export default {
  components: {
    vueDanmaku
  },
  data() {
    return {
      danmus: ['danmu1', 'danmu2', 'danmu3', 'danmu4', '...'],
      config: {
        channels: 5,
        loop: true,
        speed: 5,
        fontSize: 20
      }
    }
  }
}
</script>

<style lang="less" scoped>

</style>

**Comment by lcy7** [comment]
<template>
  <div>
    <vue-danmaku ref="danmaku" :danmus="danmus" :config="config" @inited="onInit">
      <slot></slot>
    </vue-danmaku>
  </div>
</template>

**Comment by lcy7** [comment]
<template>
  <div>
    <vue-danmaku ref="danmaku" :danmus="danmus" :config="config" @inited="onInit">
      <slot></slot>
    </vue-danmaku>
  </div>
</template>

**Comment by lcy7** [comment]
`<template>
  <div>
    <vue-danmaku ref="danmaku" :danmus="danmus" :config="config" @inited="onInit">
      <slot></slot>
    </vue-danmaku>
  </div>
</template>`

**Comment by lcy7** [comment]
`<template>`

**Comment by lcy7** [comment]
`<template>
  <div>
    <vue-danmaku ref="danmaku" :danmus="danmus" :config="config" @inited="onInit">
      <slot></slot>
    </vue-danmaku>
  </div>
</template>`

**Comment by lcy7** [comment]
`<template>
  <div>
    <vue-danmaku ref="danmaku" :danmus="danmus" :config="config" @inited="onInit">
      <slot></slot>
    </vue-danmaku>
  </div>
</template>

<script>
import vueDanmaku from 'vue-danmaku'
export default {
  components: {
    vueDanmaku
  },
  data() {
    return {
      danmus: ['danmu1', 'danmu2', 'danmu3', 'danmu4', '...'],
      config: {
        channels: 5,
        loop: true,
        speed: 5,
        fontSize: 20
      }
    }
  }
}
</script>

<style lang="less" scoped>

</style>`

**Comment by lcy7** [comment]
`<template>`
`<div>`

**Comment by lcy7** [comment]
`<template>`
` <div>`
`<vue-danmaku ref="danmaku" :danmus="danmus" :config="config" @inited="onInit">`
`<slot></slot>`
`</vue-danmaku>`
`</div>`
`</template>`

`<script>`
`import vueDanmaku from 'vue-danmaku'`
`export default {`
` components: {`
`vueDanmaku`
`},`
` data() {`
`return {`
`danmus: ['danmu1', 'danmu2', 'danmu3', 'danmu4', '...'],`
` config: {`
`        channels: 5,`
`loop: true,`
` speed: 5,`
`fontSize: 20`
``
``

**Comment by hellodigua** [comment]
看看package.json呢

**Comment by lcy7** [comment]
> 看看package.json呢
`{
  "name": "tk_pc",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "axios": "^0.21.1",
    "core-js": "^3.6.5",
    "postcss-pxtorem": "^5.1.1",
    "vue": "^2.6.11",
    "vue-baberrage": "^3.2.4",
    "vue-danmaku": "^0.1.0",
    "vue-router": "^3.2.0",
    "vuex": "^3.4.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/eslint-config-standard": "^5.1.2",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.0",
    "eslint-plugin-vue": "^6.2.2",
    "less": "^3.0.4",
    "less-loader": "^5.0.0",
    "vue-template-compiler": "^2.6.11"
  }
}
`

**Comment by hellodigua** [comment]
Emmmmmm不好意思是因为上次版本发布目录错了导致的，请下载安装0.1.1版本
```
npm i vue-danmaku@0.1.1 -S
```
应该就好了

**Comment by lcy7** [comment]
好了，感谢
