### ISSUE TITLE
获取不到容器宽高

### ISSUE THREAD

**Issue by Gavin-vue** [hellodigua/vue-danmaku#60]
已经设置了尺寸，但是报错获取不到容器宽高
 <danmaku ref="danmakuRef" 
                    v-model:danmus="problemList" 
                    :speeds="40"   use-slot loop :channels="3" style="height:167px; width:832px;">
请问怎么回事

**Comment by hellodigua** [comment]
在调用绘制弹幕方法前，打印一下父级容器，看看宽高是否正常，或者直接style给组件的宽高写死试试

**Comment by koro9** [comment]
直接style给组件的宽高写死，刷新页面还是会报错 ’获取不到容器宽高‘，正常路由进来不会报错

**Comment by hellodigua** [comment]
> 直接style给组件的宽高写死，刷新页面还是会报错 ’获取不到容器宽高‘，正常路由进来不会报错

请提供可复现的demo，我看看为什么

**Comment by hellodigua** [comment]
> 直接style给组件的宽高写死，刷新页面还是会报错 ’获取不到容器宽高‘，正常路由进来不会报错

请提供可复现的demo，我看看为什么 @koro9
