### ISSUE TITLE
是否支持小程序

### ISSUE THREAD

**Issue by Gavin-vue** [hellodigua/vue-danmaku#62]
请问是否支持小程序

**Comment by hellodigua** [comment]
你好，不打算支持

**Comment by Gavin-vue** [comment]
请问有小程序弹幕组件推荐吗？

**Comment by hellodigua** [comment]
搜了一下，基本都是三四年前的了，这个其实可以自己实现吧，你阅读一下源码，很好实现的，一共就一个文件三四百行

**Comment by Gavin-vue** [comment]
好的，谢谢！

**Comment by Gavin-vue** [comment]
您好，TypeError: Cannot read property 'offsetWidth' of undefined    at VueComponent.initCore 
我把源码引入之后报这个错误

**Comment by hellodigua** [comment]
你需要研究一下offsetWidth所属的dom为什么没有获取到的问题

**Comment by Gavin-vue** [comment]
小程序中没有dom，尝试了下不好改，请问你看的小程序弹幕插件是哪个哈，我来看下，我这边还没找到嘞

**Comment by hellodigua** [comment]
官方不就有吗，https://developers.weixin.qq.com/miniprogram/dev/platform-capabilities/extended/component-plus/barrage.html

**Comment by Gavin-vue** [comment]
这个是视频组件上的弹幕， 不是单纯的弹幕。

**Comment by hellodigua** [comment]
它实际是可以在view中使用
