### ISSUE TITLE
源码有错误

### ISSUE THREAD

**Issue by clh007** [hellodigua/vue-danmaku#63]
### 问题

![image](https://github.com/user-attachments/assets/100c4211-f665-412f-8b24-37e00b60c3d6)

### 代码实现

改成这样行不。

```
 timer = Number(setInterval(() => draw(), danmaku.debounce))
```

**Comment by hellodigua** [comment]
谢谢，已修改，参考该文：https://juejin.cn/post/6930791218955845640
