### ISSUE TITLE
弹幕会横向抖动：我使用的是文档中最简单的示例，抖动幅度挺明显的

### ISSUE THREAD

**Issue by chan-max** [hellodigua/vue-danmaku#64]
### 问题

请在此描述你的问题

### 代码实现

在此附上你遇到问题的代码或代码截图。

```

``` 

### 环境

 - vue-danmaku 版本: [e.g. v1.0.3]
 - Vue 版本: [e.g. v2.0, v2.5, v2.6]

**Comment by hellodigua** [comment]
请附上所用的版本以及示例Demo，最好描述场景，我没有复现
