### ISSUE TITLE
使用 isSuspend 悬停弹幕时，鼠标刚覆盖时 元素会向右后退一点，不知道是视觉效果或是其他问题

### ISSUE THREAD

**Issue by chan-max** [hellodigua/vue-danmaku#65]
### 问题

请在此描述你的问题

### 代码实现

在此附上你遇到问题的代码或代码截图。

```

``` 

### 环境

 - vue-danmaku 版本: [e.g. v1.0.3]
 - Vue 版本: [e.g. v2.0, v2.5, v2.6]

**Comment by hellodigua** [comment]
请附上所用的版本以及示例Demo
