### ISSUE TITLE
开启loop配置后自己生成大量数据

### ISSUE THREAD

**Issue by yangcheng0111** [hellodigua/vue-danmaku#66]
### 问题

只有一条数据，添加loop配置为true，生成大量相同数据，导致页面出现大量弹幕，卡死
未添加：
![image](https://github.com/user-attachments/assets/6fe165da-f921-48ca-afe8-9021c9295350)
![image](https://github.com/user-attachments/assets/4bc0405d-1f0a-42d0-ac37-d38a216e56cc)

添加loop：
![image](https://github.com/user-attachments/assets/13ce48d7-235c-43f4-8939-2f6e32033292)

![image](https://github.com/user-attachments/assets/70fea256-1918-4974-9579-71e2b56b477e)

**Comment by hellodigua** [comment]
这个其实是正常预期，开启loop会弹幕就会不断的重复插入，重复插入的频率是通过debounce控制的，默认是100ms插入一条，你如果希望出现的慢一点，可以将debounce设置的大一些即可，比如设置5000ms
