### ISSUE TITLE
能否支持弹幕一开始就占满中间，而不是一开始从右侧出来，导致左侧很空

### ISSUE THREAD

**Issue by 21236774** [hellodigua/vue-danmaku#67]
### 问题

能否支持弹幕一开始就占满中间，而不是一开始从右侧出来，导致左侧很空？

### 代码实现

使用v-show不行，显示获取不到元素宽度

```

``` 

### 环境

 - vue-danmaku 版本: ["vue3-danmaku": "^1.6.1"]
 - Vue 版本: ["vue": "^3.2.47"]

**Comment by hellodigua** [comment]
这个很简单，你算一下弹幕滚动过屏幕的平均时间，然后延迟个几秒再显示弹幕就好了

**Comment by 21236774** [comment]
不能一开始就显示吗？隐藏几秒体验不好，而且这个是大屏，要五秒左右才能填满屏幕

**Comment by 21236774** [comment]
可以了，还是用的hide，改变了一下方式，感谢大佬，没注意看api
