### ISSUE TITLE
当 danmus为空，loop为false 时，我给danmus添加数据，没有弹幕显示，但是loop设置为true又有了，但是插槽取不到content的值

### ISSUE THREAD

**Issue by lcy7** [hellodigua/vue-danmaku#8]
`<template>`
`  <div class="barrage-container">`
`    <vue-danmaku ref="danmaku" :danmus="danmus" :config="config">`
    
`    <template v-slot:dm="{ index, danmu }">`
`      <span class="danmu-item">111{{index}}{{ danmu.content }}</span>`
`    </template>`
`  </vue-danmaku>`
`  </div>`
`</template>`

`<script>`
`import vueDanmaku from 'vue-danmaku'`
`import { getBarrageList } from '@/api/index'`
`export default {`
`  components: {`
    `vueDanmaku`
  `},`
`  data() {`
`    return {`
    `  danmus: [],`
`      config: {`
`        slot: true,`
`        channels: 5,`
`        loop: false,`
`        speed: 5`
`      },`
`      barrageList: [],`
`      timer: null`
`    }`
`  },`
`  mounted() {`
`    this.getBarrageList()`
`  },`
`  methods: {`
`    getBarrageList() {`
`      this.danmus = [{ content: 222 }]`
`      this.$nextTick(() => {`
`        this.$refs.danmaku.play()`
`      })`
`    }`
`  }`
`}`
`</script>`

**Comment by hellodigua** [comment]
第一个问题： loop为false 时，我给danmus添加数据，没有弹幕显示

这是个BUG，已经在0.3.4中修复了

**Comment by hellodigua** [comment]
> 但是插槽取不到content的值

这是因为danmu数据暂未支持异步配置，在0.3.5中补充了这部分功能

你可以重新安装0.3.5，然后就没问题了

**Comment by lcy7** [comment]
Can't find package vue-danmaku@^0.3.5

**Comment by lcy7** [comment]
好的，感谢，家里面网不好，我明天到公司试试

**Comment by hellodigua** [comment]
@lcy7 更新了0.3.6，这个应该可以了
